browser=firefox
url=https://hrm.neotechacademy.com
#url=https://demoqa.com/select-menu
#url=https://neotech.vercel.app/sis-login
#url=https://www.facebook.com/r.php
username=admin
password=Neotech@123